# Generated by Django 3.0.14 on 2021-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_image', models.ImageField(upload_to='pill_ai/input/%Y/%m/%d')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='pill_ai/output/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
