# Generated by Django 3.0.14 on 2021-12-06 14:28

from django.db import migrations, models
import pill_ai.models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnnimage',
            name='output_image',
        ),
        migrations.AlterField(
            model_name='dnnimage',
            name='input_image',
            field=models.ImageField(upload_to=pill_ai.models.file_upload_path_for_db),
        ),
    ]
