# Generated by Django 3.0.14 on 2021-12-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pill_ai', '0003_auto_20211207_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnnimage',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dnnimage',
            name='status_mesg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
