# Generated by Django 3.0.14 on 2021-11-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmasee', '0005_auto_20211130_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='taken_time',
            field=models.TimeField(),
        ),
    ]
